"""create locations table

Revision ID: 6ecaf4547213
Revises: 
Create Date: 2025-11-11 14:51:43.008862

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6ecaf4547213"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE SCHEMA IF NOT EXISTS earthgazer")

    op.create_table("locations",
    sa.Column("id", sa.Integer(), nullable=False),
    sa.Column("name", sa.String(), nullable=False),
    sa.Column("longitude", sa.Float(), nullable=False),
    sa.Column("latitude", sa.Float(), nullable=False),
    sa.Column("from_date", sa.DateTime(), server_default="now()", nullable=False),
    sa.Column("to_date", sa.DateTime(), server_default="now()", nullable=False),
    sa.PrimaryKeyConstraint("id"),
    schema="earthgazer"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("locations", schema="earthgazer")
    # ### end Alembic commands ###
