"""add_processed_images_table

Revision ID: 7e8016d0403e
Revises: 3d91bbc55add
Create Date: 2026-01-30 01:27:28.658559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e8016d0403e'
down_revision: Union[str, Sequence[str], None] = '3d91bbc55add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=False),
    sa.Column('image_type', sa.Enum('NDVI', 'RGB', 'STACKED', name='imagetype'), nullable=False),
    sa.Column('local_path', sa.String(length=500), nullable=False),
    sa.Column('gcloud_path', sa.String(length=500), nullable=True),
    sa.Column('bands_used', sa.String(length=200), nullable=True),
    sa.Column('bounds_used', sa.String(length=200), nullable=True),
    sa.Column('processing_version', sa.String(length=50), nullable=False),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('local_available', sa.Boolean(), nullable=False),
    sa.Column('gcloud_available', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.Column('last_verified', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='earthgazer'
    )
    op.create_index(op.f('ix_earthgazer_processed_images_capture_id'), 'processed_images', ['capture_id'], unique=False, schema='earthgazer')
    op.create_index(op.f('ix_earthgazer_processed_images_image_type'), 'processed_images', ['image_type'], unique=False, schema='earthgazer')
    op.create_index('ix_processed_images_capture_available', 'processed_images', ['capture_id', 'local_available'], unique=False, schema='earthgazer')
    op.create_index('ix_processed_images_capture_type', 'processed_images', ['capture_id', 'image_type'], unique=False, schema='earthgazer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_processed_images_capture_type', table_name='processed_images', schema='earthgazer')
    op.drop_index('ix_processed_images_capture_available', table_name='processed_images', schema='earthgazer')
    op.drop_index(op.f('ix_earthgazer_processed_images_image_type'), table_name='processed_images', schema='earthgazer')
    op.drop_index(op.f('ix_earthgazer_processed_images_capture_id'), table_name='processed_images', schema='earthgazer')
    op.drop_table('processed_images', schema='earthgazer')
    # ### end Alembic commands ###
