"""add_task_tracking_tables

Revision ID: 827538c95467
Revises: 9af239edfa95
Create Date: 2026-01-14 08:54:42.684995

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '827538c95467'
down_revision: Union[str, Sequence[str], None] = '9af239edfa95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processing_jobs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('job_id', sa.String(length=255), nullable=False),
    sa.Column('job_type', sa.String(length=100), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'PARTIAL', name='processingjobstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('total_tasks', sa.Integer(), nullable=False),
    sa.Column('completed_tasks', sa.Integer(), nullable=False),
    sa.Column('failed_tasks', sa.Integer(), nullable=False),
    sa.Column('job_metadata', sa.String(length=2000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='earthgazer'
    )
    op.create_index(op.f('ix_earthgazer_processing_jobs_capture_id'), 'processing_jobs', ['capture_id'], unique=False, schema='earthgazer')
    op.create_index(op.f('ix_earthgazer_processing_jobs_job_id'), 'processing_jobs', ['job_id'], unique=True, schema='earthgazer')
    op.create_table('task_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('task_id', sa.String(length=255), nullable=False),
    sa.Column('task_name', sa.String(length=255), nullable=False),
    sa.Column('capture_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'STARTED', 'SUCCESS', 'FAILURE', 'RETRY', 'REVOKED', name='taskstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default='now()', nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('result', sa.String(length=1000), nullable=True),
    sa.Column('error', sa.String(length=2000), nullable=True),
    sa.Column('retries', sa.Integer(), nullable=False),
    sa.Column('worker_name', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    schema='earthgazer'
    )
    op.create_index(op.f('ix_earthgazer_task_executions_capture_id'), 'task_executions', ['capture_id'], unique=False, schema='earthgazer')
    op.create_index(op.f('ix_earthgazer_task_executions_task_id'), 'task_executions', ['task_id'], unique=True, schema='earthgazer')
    op.create_index(op.f('ix_earthgazer_task_executions_task_name'), 'task_executions', ['task_name'], unique=False, schema='earthgazer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_earthgazer_task_executions_task_name'), table_name='task_executions', schema='earthgazer')
    op.drop_index(op.f('ix_earthgazer_task_executions_task_id'), table_name='task_executions', schema='earthgazer')
    op.drop_index(op.f('ix_earthgazer_task_executions_capture_id'), table_name='task_executions', schema='earthgazer')
    op.drop_table('task_executions', schema='earthgazer')
    op.drop_index(op.f('ix_earthgazer_processing_jobs_job_id'), table_name='processing_jobs', schema='earthgazer')
    op.drop_index(op.f('ix_earthgazer_processing_jobs_capture_id'), table_name='processing_jobs', schema='earthgazer')
    op.drop_table('processing_jobs', schema='earthgazer')
    # ### end Alembic commands ###
