"""update string lengths

Revision ID: 9af239edfa95
Revises: e77931b840a7
Create Date: 2025-11-12 04:17:41.497924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9af239edfa95'
down_revision: Union[str, Sequence[str], None] = 'e77931b840a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capture_data', 'main_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='earthgazer')
    op.alter_column('capture_data', 'secondary_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='earthgazer')
    op.alter_column('capture_data', 'mission_id',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=False,
               schema='earthgazer')
    op.alter_column('capture_data', 'base_url',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=False,
               schema='earthgazer')
    op.alter_column('capture_data', 'mgrs_tile',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=100),
               existing_nullable=True,
               schema='earthgazer')
    op.alter_column('capture_data', 'backup_location',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=500),
               existing_nullable=True,
               schema='earthgazer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('capture_data', 'backup_location',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True,
               schema='earthgazer')
    op.alter_column('capture_data', 'mgrs_tile',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=True,
               schema='earthgazer')
    op.alter_column('capture_data', 'base_url',
               existing_type=sa.String(length=500),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False,
               schema='earthgazer')
    op.alter_column('capture_data', 'mission_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               schema='earthgazer')
    op.alter_column('capture_data', 'secondary_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               schema='earthgazer')
    op.alter_column('capture_data', 'main_id',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False,
               schema='earthgazer')
    # ### end Alembic commands ###
