"""update location columns and add capture data tracking

Revision ID: e77931b840a7
Revises: 6ecaf4547213
Create Date: 2025-11-12 04:03:05.671527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e77931b840a7'
down_revision: Union[str, Sequence[str], None] = '6ecaf4547213'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capture_data',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('main_id', sa.String(length=30), nullable=False),
    sa.Column('secondary_id', sa.String(length=30), nullable=False),
    sa.Column('mission_id', sa.String(length=30), nullable=False),
    sa.Column('sensing_time', sa.DateTime(), nullable=False),
    sa.Column('north_lat', sa.Float(), nullable=False),
    sa.Column('south_lat', sa.Float(), nullable=False),
    sa.Column('west_lon', sa.Float(), nullable=False),
    sa.Column('east_lon', sa.Float(), nullable=False),
    sa.Column('base_url', sa.String(length=120), nullable=False),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.Column('radiometric_measure', sa.Enum('RADIANCE', 'REFLECTANCE', 'DN', name='radiometricmeasure'), nullable=True),
    sa.Column('athmospheric_reference_level', sa.Enum('TOA', 'BOA', name='atmosphericreferencelevel'), nullable=True),
    sa.Column('mgrs_tile', sa.String(length=30), nullable=True),
    sa.Column('wrs_path', sa.Integer(), nullable=True),
    sa.Column('wrs_row', sa.Integer(), nullable=True),
    sa.Column('data_type', sa.String(length=30), nullable=True),
    sa.Column('backed_up', sa.Boolean(), nullable=False),
    sa.Column('backup_date', sa.DateTime(), nullable=True),
    sa.Column('backup_location', sa.String(length=120), nullable=True),
    sa.Column('added', sa.DateTime(), server_default='now()', nullable=False),
    sa.PrimaryKeyConstraint('id', 'main_id'),
    schema='earthgazer'
    )
    op.add_column('locations', sa.Column('active', sa.Boolean(), nullable=True), schema='earthgazer')
    op.execute("UPDATE earthgazer.locations SET active = TRUE WHERE active IS NULL")
    op.alter_column('locations', 'active', nullable=False, schema='earthgazer')
    
    op.add_column('locations', sa.Column('added', sa.DateTime(), server_default='now()', nullable=False), schema='earthgazer')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locations', 'added', schema='earthgazer')
    op.drop_column('locations', 'active', schema='earthgazer')
    op.drop_table('capture_data', schema='earthgazer')
    # ### end Alembic commands ###
